# Compiler and tools
CXX = g++
AR = ar

# Project paths
MOCK_SRC_DIR = src/stm32/mock
MOCK_BUILD_DIR = build/stm32/mock
MOCK_BUILD_INCLUDE_DIR = build/include/stm32/mock

# Include paths (exclude problematic ARM-specific CMSIS headers for mock build)
INCLUDES = -I$(MOCK_SRC_DIR) \
           -Ithird_party/CMSIS_6/CMSIS/Core/Include \
					 -Ithird_party/cmsis-device-f1/Include

# Preprocessor definitions for mock build
DEFINES = -DSTM32F103xB -DEMBYS_MOCK_BUILD

# Compiler flags
CXXFLAGS = -Wall -Wextra -Werror -std=c++20 -O0 -g3 -MMD -MP $(INCLUDES) $(DEFINES)
ARFLAGS = rcs

# Find all source files in mock directory and subdirectories
MOCK_SOURCES = $(shell find $(MOCK_SRC_DIR) -name "*.cpp")
MOCK_OBJECTS = $(patsubst $(MOCK_SRC_DIR)/%.cpp,$(MOCK_BUILD_DIR)/%.o,$(MOCK_SOURCES))

# Find all header files in mock directory and subdirectories
MOCK_HEADERS = $(shell find $(MOCK_SRC_DIR) -name "*.hpp")
MOCK_HEADERS += $(shell find $(MOCK_SRC_DIR) -name "*.h")
MOCK_INSTALLED_HEADERS = $(patsubst $(MOCK_SRC_DIR)/%,$(MOCK_BUILD_INCLUDE_DIR)/%,$(MOCK_HEADERS))

# Static library target
MOCK_LIBRARY = $(MOCK_BUILD_DIR)/libstm32-mock.a

# Build STM32 mock static library
.PHONY: stm32-mock
stm32-mock: $(MOCK_LIBRARY) $(MOCK_INSTALLED_HEADERS)

$(MOCK_LIBRARY): $(MOCK_OBJECTS)
	@mkdir -p $(dir $@)
	@echo "Creating static library: $@"
	$(AR) $(ARFLAGS) $@ $^

$(MOCK_BUILD_INCLUDE_DIR)/%.hpp: $(MOCK_SRC_DIR)/%.hpp
	@mkdir -p $(dir $@)
	@echo "Installing header: $@"
	@cp $< $@

$(MOCK_BUILD_INCLUDE_DIR)/%.h: $(MOCK_SRC_DIR)/%.h
	@mkdir -p $(dir $@)
	@echo "Installing header: $@"
	@cp $< $@

# Compile source files to object files
$(MOCK_BUILD_DIR)/%.o: $(MOCK_SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	@echo "Compiling: $<"
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Include dependency files (auto-generated by -MMD -MP flags)
-include $(MOCK_OBJECTS:.o=.d)
