# Compiler and tools
CXX = g++
AR = ar

# Project paths
SIM_SRC_DIR = src/stm32/sim
SIM_BUILD_DIR = build/stm32/sim
SIM_BUILD_INCLUDE_DIR = build/include/stm32/sim

INCLUDES = -I$(SIM_SRC_DIR) \
           -Ithird_party/CMSIS_6/CMSIS/Core/Include \
					 -Ithird_party/cmsis-device-f1/Include

DEFINES = -DSTM32F103xB -DEMBYS_SIM_BUILD

# Compiler flags
CXXFLAGS = -Wall -Wextra -Werror -std=c++20 -O0 -g3 -MMD -MP $(INCLUDES) $(DEFINES)
ARFLAGS = rcs

# Find all source files in sim directory and subdirectories
SIM_SOURCES = $(shell find $(SIM_SRC_DIR) -name "*.cpp")
SIM_OBJECTS = $(patsubst $(SIM_SRC_DIR)/%.cpp,$(SIM_BUILD_DIR)/%.o,$(SIM_SOURCES))

# Find all header files in sim directory and subdirectories
SIM_HEADERS = $(shell find $(SIM_SRC_DIR) -name "*.hpp")
SIM_HEADERS += $(shell find $(SIM_SRC_DIR) -name "*.h")
SIM_INSTALLED_HEADERS = $(patsubst $(SIM_SRC_DIR)/%,$(SIM_BUILD_INCLUDE_DIR)/%,$(SIM_HEADERS))

# Static library target
SIM_LIBRARY = $(SIM_BUILD_DIR)/libstm32-sim.a

# Build STM32 sim static library
.PHONY: stm32-sim
stm32-sim: $(SIM_LIBRARY) $(SIM_INSTALLED_HEADERS)

$(SIM_LIBRARY): $(SIM_OBJECTS)
	@mkdir -p $(dir $@)
	@echo "Creating static library: $@"
	$(AR) $(ARFLAGS) $@ $^

$(SIM_BUILD_INCLUDE_DIR)/%.hpp: $(SIM_SRC_DIR)/%.hpp
	@mkdir -p $(dir $@)
	@echo "Installing header: $@"
	@cp $< $@

$(SIM_BUILD_INCLUDE_DIR)/%.h: $(SIM_SRC_DIR)/%.h
	@mkdir -p $(dir $@)
	@echo "Installing header: $@"
	@cp $< $@

# Compile source files to object files
$(SIM_BUILD_DIR)/%.o: $(SIM_SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	@echo "Compiling: $<"
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Include dependency files (auto-generated by -MMD -MP flags)
-include $(SIM_OBJECTS:.o=.d)
