#include <stdint.h>

extern uint32_t _estack;

void
Reset_Handler(void);

void
Default_Handler(void);

#define WEAK __attribute__((weak))
#define ALIAS(fn) __attribute__((weak, alias(#fn)))

// Cortex-M7 core exceptions
void WEAK
NMI_Handler(void) ALIAS(Default_Handler);
void WEAK
HardFault_Handler(void) ALIAS(Default_Handler);
void WEAK
MemManage_Handler(void) ALIAS(Default_Handler);
void WEAK
BusFault_Handler(void) ALIAS(Default_Handler);
void WEAK
UsageFault_Handler(void) ALIAS(Default_Handler);
void WEAK
SVC_Handler(void) ALIAS(Default_Handler);
void WEAK
DebugMon_Handler(void) ALIAS(Default_Handler);
void WEAK
PendSV_Handler(void) ALIAS(Default_Handler);
void WEAK
SysTick_Handler(void) ALIAS(Default_Handler);

// External interrupts (H743)
void WEAK
WWDG_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
PVD_AVD_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TAMP_STAMP_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
RTC_WKUP_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FLASH_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
RCC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream6_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
ADC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FDCAN1_IT0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FDCAN2_IT0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FDCAN1_IT1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FDCAN2_IT1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI9_5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM1_BRK_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM1_UP_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM1_TRG_COM_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM1_CC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C1_EV_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C1_ER_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C2_EV_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C2_ER_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPI1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPI2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
USART1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
USART2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
USART3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
EXTI15_10_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
RTC_Alarm_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM8_BRK_TIM12_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM8_UP_TIM13_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM8_TRG_COM_TIM14_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM8_CC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA1_Stream7_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FMC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SDMMC1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPI3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
UART4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
UART5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM6_DAC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM7_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
ETH_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
ETH_WKUP_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FDCAN_CAL_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream6_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2_Stream7_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
USART6_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C3_EV_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C3_ER_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
OTG_HS_EP1_OUT_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
OTG_HS_EP1_IN_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
OTG_HS_WKUP_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
OTG_HS_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DCMI_PSSI_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
RNG_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
FPU_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
UART7_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
UART8_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPI4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPI5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPI6_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SAI1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LTDC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LTDC_ER_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMA2D_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SAI2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
QUADSPI_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LPTIM1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
CEC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C4_EV_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
I2C4_ER_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SPDIF_RX_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
OTG_FS_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMAMUX1_OVR_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_Master_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_TIMA_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_TIMB_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_TIMC_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_TIMD_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_TIME_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HRTIM1_FLT_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DFSDM1_FLT0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DFSDM1_FLT1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DFSDM1_FLT2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DFSDM1_FLT3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SAI3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SWPMI1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM15_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM16_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
TIM17_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
MDIOS_WKUP_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
MDIOS_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
JPEG_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
MDMA_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SDMMC2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
HSEM1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
ADC3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
DMAMUX2_OVR_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel0_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel6_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
BDMA_Channel7_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
COMP1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LPTIM2_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LPTIM3_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LPTIM4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LPTIM5_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
LPUART1_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
CRS_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
SAI4_IRQHandler(void) ALIAS(Default_Handler);
void WEAK
WAKEUP_PIN_IRQHandler(void) ALIAS(Default_Handler);
